# render.yaml - 适用于您的 Flask 应用的完整、安全配置

services:
  # 您的主 Web 应用服务
  - type: web
    name: lingowizz-backend  # 您的服务名称
    env: python             # 指定环境为 Python
    plan: free  
    
    # 关键：构建和启动配置
    # --------------------------
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: "python -m gunicorn run:app"

    # 关键：环境变量配置
    # --------------------------
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9  # ！！！使用稳定的Python版本来避免构建错误

      - key: FLASK_ENV
        value: production  # 部署时应使用生产环境

      # --- 新增的非敏感环境变量 ---
      - key: HF_API_URL
        value: "https://mfuhb8ole0ld4d0p.us-east-1.aws.endpoints.huggingface.cloud"

      # --- 以下是需要您在Render仪表盘手动设置的【秘密】变量 ---
      # 'sync: false' 告诉Render不要从这个文件同步值，而是使用你在UI中设置的值。
      
      - key: DATABASE_URL
        sync: false  # 您的数据库连接字符串

      - key: ZHIPU_API_KEY
        sync: false  # 您的智谱AI密钥

      - key: vivo_app_id
        sync: false  # vivo的ID

      - key: vivo_app_key
        sync: false  # vivo的密钥

      # --- 新增的秘密环境变量 ---
      - key: HF_API_TOKEN
        sync: false  # 您的Hugging Face Token，是秘密！
      
      # --- Render将为您自动生成这个密钥 ---
      - key: SECRET_KEY
        generateValue: true # 让Render为您生成一个安全的、随机的Flask密钥
